/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

/**
 *
 * @author admin
 */
public class ChucNangFrame extends javax.swing.JFrame {

    /**
     * Creates new form ChucNangFrame
     */
    public ChucNangFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btTrangChu = new javax.swing.JButton();
        btThongKeKho = new javax.swing.JButton();
        btQuanLyKho = new javax.swing.JButton();
        btThongKeSach = new javax.swing.JButton();
        btThongKeVPP = new javax.swing.JButton();
        mainPN = new javax.swing.JPanel();
        pnTrangChu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        pnThongKeKho = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbVPP = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbSach = new javax.swing.JTable();
        pnQuanLyKho = new javax.swing.JPanel();
        mainGD = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        pnQuanLySach = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        tfDonGia = new javax.swing.JTextField();
        tfNhaXB = new javax.swing.JTextField();
        tfSoLuong = new javax.swing.JTextField();
        tfTenSach = new javax.swing.JTextField();
        tfMaSP = new javax.swing.JTextField();
        tfTacGia = new javax.swing.JTextField();
        TfTheLoai = new javax.swing.JTextField();
        tfNamXB = new javax.swing.JTextField();
        tfTimKiem = new javax.swing.JTextField();
        btTimKiem = new javax.swing.JButton();
        btLamMoi = new javax.swing.JButton();
        btXoaBo = new javax.swing.JButton();
        btCapNhat = new javax.swing.JButton();
        btNhapKho = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbQuanLySach = new javax.swing.JTable();
        pnQuanLyVPP = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        tfDonGia1 = new javax.swing.JTextField();
        tfNhaXB1 = new javax.swing.JTextField();
        tfSoLuong1 = new javax.swing.JTextField();
        tfTenSach1 = new javax.swing.JTextField();
        tfMaSP1 = new javax.swing.JTextField();
        tfTacGia1 = new javax.swing.JTextField();
        TfTheLoai1 = new javax.swing.JTextField();
        tfNamXB1 = new javax.swing.JTextField();
        tfTimKiem1 = new javax.swing.JTextField();
        btTimKiem1 = new javax.swing.JButton();
        btLamMoi1 = new javax.swing.JButton();
        btXoaBo1 = new javax.swing.JButton();
        btCapNhat1 = new javax.swing.JButton();
        btNhapKho1 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        tbQuanLyVPP = new javax.swing.JTable();
        pnThongKeVPP = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbThongKeVPP = new javax.swing.JTable();
        pnThongKeSach = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbThongKeSach = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btTrangChu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Anh/Screenshot 2026-05-25 095740.png"))); // NOI18N
        btTrangChu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTrangChuActionPerformed(evt);
            }
        });
        jPanel1.add(btTrangChu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        btThongKeKho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Anh/Screenshot 2026-05-25 095744.png"))); // NOI18N
        jPanel1.add(btThongKeKho, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, 60));

        btQuanLyKho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Anh/Screenshot 2026-05-25 095748.png"))); // NOI18N
        jPanel1.add(btQuanLyKho, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 80, 60));

        btThongKeSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Anh/Screenshot 2026-05-25 095752.png"))); // NOI18N
        jPanel1.add(btThongKeSach, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 80, 60));

        btThongKeVPP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Anh/Screenshot 2026-05-25 095755.png"))); // NOI18N
        jPanel1.add(btThongKeVPP, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 80, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 110, 480));

        mainPN.setLayout(new java.awt.CardLayout());

        pnTrangChu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setText("Trang Chủ");
        pnTrangChu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel2.setText("Nổi Bật");
        pnTrangChu.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel3.setText("Có gì Hot?");
        pnTrangChu.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));
        pnTrangChu.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 120, 90));
        pnTrangChu.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 120, 90));
        pnTrangChu.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, 120, 90));
        pnTrangChu.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 520, 80));

        mainPN.add(pnTrangChu, "card2");

        pnThongKeKho.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel4.setText("Thống Kê Kho");
        pnThongKeKho.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        tbVPP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã SP", "Tên", "Tồn"
            }
        ));
        jScrollPane2.setViewportView(tbVPP);

        pnThongKeKho.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 320, 260));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel5.setText("Tổng Quan Hệ Thống");
        pnThongKeKho.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Tổng Sách:");
        pnThongKeKho.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 250, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Văn Phòng Phẩm:");
        pnThongKeKho.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 240, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Tổng Tồn Kho:");
        pnThongKeKho.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 240, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Sắp Hết Hàng:");
        pnThongKeKho.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 250, 20));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel10.setText("Tình Trạng Sách Gần Đây");
        pnThongKeKho.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel11.setText("Tình Trạng Văn Phòng Phẩm Gần Đây");
        pnThongKeKho.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, -1, -1));

        tbSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã SP", "Tên", "Tồn"
            }
        ));
        jScrollPane1.setViewportView(tbSach);

        pnThongKeKho.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 320, 260));

        mainPN.add(pnThongKeKho, "card3");

        pnQuanLyKho.setLayout(new java.awt.CardLayout());

        mainGD.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton6.setText("Quản Lý Sách");
        mainGD.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 110, -1));

        jButton7.setText("Quản Lý Văn Phòng Phẩm");
        mainGD.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel14.setText("Quản Lý Kho");
        mainGD.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        pnQuanLySach.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setText("Mã Sản Phẩm");
        pnQuanLySach.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel16.setText("Tên Sách");
        pnQuanLySach.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        jLabel17.setText("Số Lượng");
        pnQuanLySach.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, -1));

        jLabel18.setText("Thể Loại");
        pnQuanLySach.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, -1, -1));

        jLabel19.setText("Đơn Giá");
        pnQuanLySach.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, -1, -1));

        jLabel20.setText("Tắc giả");
        pnQuanLySach.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel21.setText("Năm Xuất Bản");
        pnQuanLySach.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, -1, -1));

        jLabel22.setText("Nhà Xuất Bản");
        pnQuanLySach.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, -1, -1));
        pnQuanLySach.add(tfDonGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 120, -1));
        pnQuanLySach.add(tfNhaXB, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 90, 110, -1));
        pnQuanLySach.add(tfSoLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 120, -1));
        pnQuanLySach.add(tfTenSach, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 120, -1));
        pnQuanLySach.add(tfMaSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 120, -1));
        pnQuanLySach.add(tfTacGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 120, -1));
        pnQuanLySach.add(TfTheLoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 120, -1));
        pnQuanLySach.add(tfNamXB, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 120, -1));

        tfTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTimKiemActionPerformed(evt);
            }
        });
        pnQuanLySach.add(tfTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 150, -1));

        btTimKiem.setText("Tìm Kiếm");
        pnQuanLySach.add(btTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, -1, -1));

        btLamMoi.setText("Làm Mới");
        pnQuanLySach.add(btLamMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, -1, -1));

        btXoaBo.setText("Xoá Bỏ");
        pnQuanLySach.add(btXoaBo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, -1, -1));

        btCapNhat.setText("Cập Nhật");
        pnQuanLySach.add(btCapNhat, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, -1, -1));

        btNhapKho.setText("Nhập Kho");
        pnQuanLySach.add(btNhapKho, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 130, -1, -1));

        tbQuanLySach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã SP", "Tên Sách", "Số Lượng", "Đơn Giá", "Tác Giả", "Thể Loại", "Năm XB", "Nhà XB"
            }
        ));
        jScrollPane5.setViewportView(tbQuanLySach);

        pnQuanLySach.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 640, 190));

        mainGD.add(pnQuanLySach, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 640, 360));

        pnQuanLyVPP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setText("Mã Sản Phẩm");
        pnQuanLyVPP.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel24.setText("Tên Sách");
        pnQuanLyVPP.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        jLabel25.setText("Số Lượng");
        pnQuanLyVPP.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, -1));

        jLabel26.setText("Thể Loại");
        pnQuanLyVPP.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, -1, -1));

        jLabel27.setText("Đơn Giá");
        pnQuanLyVPP.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, -1, -1));

        jLabel28.setText("Tắc giả");
        pnQuanLyVPP.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel29.setText("Năm Xuất Bản");
        pnQuanLyVPP.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, -1, -1));

        jLabel30.setText("Nhà Xuất Bản");
        pnQuanLyVPP.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, -1, -1));
        pnQuanLyVPP.add(tfDonGia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 120, -1));
        pnQuanLyVPP.add(tfNhaXB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 90, 110, -1));
        pnQuanLyVPP.add(tfSoLuong1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 120, -1));
        pnQuanLyVPP.add(tfTenSach1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 120, -1));
        pnQuanLyVPP.add(tfMaSP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 120, -1));
        pnQuanLyVPP.add(tfTacGia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 120, -1));
        pnQuanLyVPP.add(TfTheLoai1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 120, -1));
        pnQuanLyVPP.add(tfNamXB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 120, -1));

        tfTimKiem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTimKiem1ActionPerformed(evt);
            }
        });
        pnQuanLyVPP.add(tfTimKiem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 150, -1));

        btTimKiem1.setText("Tìm Kiếm");
        pnQuanLyVPP.add(btTimKiem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, -1, -1));

        btLamMoi1.setText("Làm Mới");
        pnQuanLyVPP.add(btLamMoi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, -1, -1));

        btXoaBo1.setText("Xoá Bỏ");
        pnQuanLyVPP.add(btXoaBo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, -1, -1));

        btCapNhat1.setText("Cập Nhật");
        pnQuanLyVPP.add(btCapNhat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, -1, -1));

        btNhapKho1.setText("Nhập Kho");
        pnQuanLyVPP.add(btNhapKho1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 130, -1, -1));

        tbQuanLyVPP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã SP", "Tên Sách", "Số Lượng", "Đơn Giá", "Tác Giả", "Thể Loại", "Năm XB", "Nhà XB"
            }
        ));
        jScrollPane6.setViewportView(tbQuanLyVPP);

        pnQuanLyVPP.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 640, 190));

        mainGD.add(pnQuanLyVPP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 640, 360));

        pnQuanLyKho.add(mainGD, "card2");

        mainPN.add(pnQuanLyKho, "card6");

        pnThongKeVPP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel13.setText("Thống Kê Văn Phòng Phẩm");
        pnThongKeVPP.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        tbThongKeVPP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã SP", "Tên Sách", "Số Lượng", "Đơn Giá", "Tác Giả", "Thể Loại", "Năm XB", "Nhà XB"
            }
        ));
        jScrollPane4.setViewportView(tbThongKeVPP);

        pnThongKeVPP.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 640, 400));

        mainPN.add(pnThongKeVPP, "card5");

        pnThongKeSach.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel12.setText("Thống Kê Sách");
        pnThongKeSach.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        tbThongKeSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã SP", "Tên Sách", "Số Lượng", "Đơn Giá", "Tác Giả", "Thể Loại", "Năm XB", "Nhà XB"
            }
        ));
        jScrollPane3.setViewportView(tbThongKeSach);

        pnThongKeSach.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 640, 400));

        mainPN.add(pnThongKeSach, "card4");

        getContentPane().add(mainPN, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 640, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btTrangChuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTrangChuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btTrangChuActionPerformed

    private void tfTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTimKiemActionPerformed

    private void tfTimKiem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTimKiem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTimKiem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChucNangFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChucNangFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChucNangFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChucNangFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChucNangFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TfTheLoai;
    private javax.swing.JTextField TfTheLoai1;
    private javax.swing.JButton btCapNhat;
    private javax.swing.JButton btCapNhat1;
    private javax.swing.JButton btLamMoi;
    private javax.swing.JButton btLamMoi1;
    private javax.swing.JButton btNhapKho;
    private javax.swing.JButton btNhapKho1;
    private javax.swing.JButton btQuanLyKho;
    private javax.swing.JButton btThongKeKho;
    private javax.swing.JButton btThongKeSach;
    private javax.swing.JButton btThongKeVPP;
    private javax.swing.JButton btTimKiem;
    private javax.swing.JButton btTimKiem1;
    private javax.swing.JButton btTrangChu;
    private javax.swing.JButton btXoaBo;
    private javax.swing.JButton btXoaBo1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JPanel mainGD;
    private javax.swing.JPanel mainPN;
    private javax.swing.JPanel pnQuanLyKho;
    private javax.swing.JPanel pnQuanLySach;
    private javax.swing.JPanel pnQuanLyVPP;
    private javax.swing.JPanel pnThongKeKho;
    private javax.swing.JPanel pnThongKeSach;
    private javax.swing.JPanel pnThongKeVPP;
    private javax.swing.JPanel pnTrangChu;
    private javax.swing.JTable tbQuanLySach;
    private javax.swing.JTable tbQuanLyVPP;
    private javax.swing.JTable tbSach;
    private javax.swing.JTable tbThongKeSach;
    private javax.swing.JTable tbThongKeVPP;
    private javax.swing.JTable tbVPP;
    private javax.swing.JTextField tfDonGia;
    private javax.swing.JTextField tfDonGia1;
    private javax.swing.JTextField tfMaSP;
    private javax.swing.JTextField tfMaSP1;
    private javax.swing.JTextField tfNamXB;
    private javax.swing.JTextField tfNamXB1;
    private javax.swing.JTextField tfNhaXB;
    private javax.swing.JTextField tfNhaXB1;
    private javax.swing.JTextField tfSoLuong;
    private javax.swing.JTextField tfSoLuong1;
    private javax.swing.JTextField tfTacGia;
    private javax.swing.JTextField tfTacGia1;
    private javax.swing.JTextField tfTenSach;
    private javax.swing.JTextField tfTenSach1;
    private javax.swing.JTextField tfTimKiem;
    private javax.swing.JTextField tfTimKiem1;
    // End of variables declaration//GEN-END:variables
}
