/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

/**
 *
 * @author admin
 */
public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        txtUserid = new javax.swing.JTextField();
        Next = new javax.swing.JButton();
        NenLogin1 = new javax.swing.JLabel();
        NenLogin2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Anh/Screenshot 2026-05-25 074105.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jLabel2.setText("Sign in");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, -1));

        txtPass.setText("jPasswordField1");
        txtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassActionPerformed(evt);
            }
        });
        getContentPane().add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 200, 40));

        txtUserid.setText("USERID");
        txtUserid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUseridActionPerformed(evt);
            }
        });
        getContentPane().add(txtUserid, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 200, 40));

        Next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Anh/Screenshot 2026-05-25 075236.png"))); // NOI18N
        Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextActionPerformed(evt);
            }
        });
        getContentPane().add(Next, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 50, 40));

        NenLogin1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Anh/Screenshot 2026-05-25 072549.png"))); // NOI18N
        getContentPane().add(NenLogin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 0, -1, -1));

        NenLogin2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Anh/Screenshot 2026-05-25 073848.png"))); // NOI18N
        getContentPane().add(NenLogin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 268, 483));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUseridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUseridActionPerformed
        // TODO add your handling code here:
        txtPass.requestFocus();
    }//GEN-LAST:event_txtUseridActionPerformed

    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed
        // TODO add your handling code here:
        Next.doClick();
    }//GEN-LAST:event_txtPassActionPerformed

    private void NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextActionPerformed
        // TODO add your handling code here:
        String userid = txtUserid.getText().trim();
        String password = new String(txtPass.getPassword()).trim();

        // 1. Kiểm tra xem người dùng đã nhập chưa
        if (userid.isEmpty() || userid.equals("USERID") || 
            password.isEmpty() || password.equals("PASSWORD")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ USERID và PASSWORD!");
            return; 
        }

        // 2. Kết nối CSDL để kiểm tra đăng nhập
        try {
            // Gọi hàm kết nối từ class DBConnection của bạn
            java.sql.Connection conn = util.DBConnection.getConnection();
            
            if (conn == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "Lỗi kết nối đến SQL Server! Vui lòng kiểm tra lại DBConnection.");
                return;
            }

            // Câu lệnh SQL: Bạn nhớ thay đổi tên bảng (TaiKhoan) và tên cột (UserID, Password) 
            // cho đúng với thiết kế bảng trong database "Quan_Ly_Kho_Hang" của bạn nhé.
            String sql = "SELECT * FROM TaiKhoan WHERE UserID = ? AND Password = ?";
            
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, userid);
            pst.setString(2, password);
            
            java.sql.ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                // Nếu tìm thấy dòng dữ liệu -> Đăng nhập đúng
                javax.swing.JOptionPane.showMessageDialog(this, "Đăng nhập thành công!");
                
                // Tắt form đăng nhập
                this.dispose(); 
                
                // Mở cửa sổ chính (Bỏ comment khi bạn đã tạo Form Main)
                // Main mainForm = new Main();
                // mainForm.setVisible(true);
            } else {
                // Không tìm thấy -> Sai tài khoản/mật khẩu
                javax.swing.JOptionPane.showMessageDialog(this, "USERID hoặc PASSWORD không đúng!", "Lỗi", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
            
            // Đóng kết nối
            rs.close();
            pst.close();
            conn.close();
            
        } catch (Exception e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Lỗi truy vấn: " + e.getMessage());
        }
    }//GEN-LAST:event_NextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NenLogin1;
    private javax.swing.JLabel NenLogin2;
    private javax.swing.JButton Next;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUserid;
    // End of variables declaration//GEN-END:variables
}
