/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import dao.SachDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Sach;
import service.QuanLyKho;

public class MenuFrame extends javax.swing.JFrame {

    private QuanLyKho quanLyKhoService = new QuanLyKho();
    private SachDAO sachDAO =new SachDAO();
    private DefaultTableModel tableModel;
    
    
    
    public MenuFrame() {
        initComponents();
        // Lấy model của bảng đã vẽ và gọi hàm nạp dữ liệu
        tableModel = (javax.swing.table.DefaultTableModel) tblKhoHang.getModel();
        loadDataToTable();
    }
    
    // Hàm nạp dữ liệu lên Bảng (Tự viết thêm vào đây)
    private void loadDataToTable() {
        tableModel.setRowCount(0); // Xóa trắng bảng cũ
        
        // Gọi thẳng DAO để lấy danh sách vì Service không hỗ trợ trả về List
        java.util.ArrayList<model.Sach> danhSach = sachDAO.selectAll();
        
        if (danhSach != null) {
            for (model.Sach s : danhSach) {
                // CHÚ Ý: Đổi tên các hàm getMasp(), getSoluong()... 
                // cho đúng với code trong file model.Sach.java của bạn nhé
                tableModel.addRow(new Object[]{
                    s.getMasp(), 
                    s.getTensp(), 
                    s.getSoluong(), 
                    s.getDongia() 
                });
            }
        }
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        lbMaSP = new javax.swing.JLabel();
        lbTenSP = new javax.swing.JLabel();
        lbSoLuong = new javax.swing.JLabel();
        lbDonGia = new javax.swing.JLabel();
        txtMaSP = new javax.swing.JTextField();
        txtTenSP = new javax.swing.JTextField();
        txtSoLuong = new javax.swing.JTextField();
        txtDonGia = new javax.swing.JTextField();
        btThem = new javax.swing.JButton();
        btCapNhat = new javax.swing.JButton();
        btXoa = new javax.swing.JButton();
        btNhapHang = new javax.swing.JButton();
        btTimKiem = new javax.swing.JButton();
        btThoat = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKhoHang = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbMaSP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbMaSP.setText("Mã sản phẩm :");

        lbTenSP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbTenSP.setText("Tên sản phẩm :");

        lbSoLuong.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbSoLuong.setText("Số lượng         :");

        lbDonGia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbDonGia.setText("Đơn giá           :");

        txtMaSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaSPActionPerformed(evt);
            }
        });

        txtTenSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenSPActionPerformed(evt);
            }
        });

        txtSoLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoLuongActionPerformed(evt);
            }
        });

        txtDonGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDonGiaActionPerformed(evt);
            }
        });

        btThem.setText("Thêm");
        btThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemActionPerformed(evt);
            }
        });

        btCapNhat.setText("Cập Nhật");
        btCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCapNhatActionPerformed(evt);
            }
        });

        btXoa.setText("Xoá");
        btXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaActionPerformed(evt);
            }
        });

        btNhapHang.setText("Nhập Hàng");
        btNhapHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNhapHangActionPerformed(evt);
            }
        });

        btTimKiem.setText("Tìm Kiếm");
        btTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTimKiemActionPerformed(evt);
            }
        });

        btThoat.setText("Thoát");
        btThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThoatActionPerformed(evt);
            }
        });

        tblKhoHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã Sản Phẩm", "Tên Sản Phẩm", "Số Lượng", "Đơn Giá"
            }
        ));
        jScrollPane1.setViewportView(tblKhoHang);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbTenSP)
                                    .addComponent(lbSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(163, 163, 163)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(160, 160, 160)
                                .addComponent(txtMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(155, 155, 155))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btThem)
                            .addGap(40, 40, 40)
                            .addComponent(btCapNhat)
                            .addGap(46, 46, 46)
                            .addComponent(btXoa)
                            .addGap(42, 42, 42)
                            .addComponent(btNhapHang)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btTimKiem))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btThoat)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMaSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTenSP)
                    .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSoLuong)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDonGia)
                    .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btThem)
                    .addComponent(btCapNhat)
                    .addComponent(btXoa)
                    .addComponent(btNhapHang)
                    .addComponent(btTimKiem))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btThoat)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaSPActionPerformed

    private void txtTenSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenSPActionPerformed

    private void txtSoLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoLuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoLuongActionPerformed

    //nút thoát
    private void btThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThoatActionPerformed
       System.exit(0); // TODO add your handling code here:
    }//GEN-LAST:event_btThoatActionPerformed

    //nút thêm
    private void btThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemActionPerformed
        try {
            String ma = txtMaSP.getText();
            String ten = txtTenSP.getText();
            int soLuong = Integer.parseInt(txtSoLuong.getText());
            double donGia = Double.parseDouble(txtDonGia.getText()); 

            // Điền giả "" cho thể loại và 0 cho năm xuất bản vì UI không có ô nhập
            Sach sachMoi = new Sach(ma, ten, soLuong, donGia, "", 0); 
            quanLyKhoService.themSach(sachMoi); 
            
            JOptionPane.showMessageDialog(this, "Thêm sách thành công!");
            loadDataToTable(); 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi nhập liệu! Vui lòng kiểm tra lại số lượng/đơn giá.");
        }
    }//GEN-LAST:event_btThemActionPerformed

    //nút cập nhật
    private void btCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCapNhatActionPerformed
        // TODO add your handling code here:
        try {
            String ma = txtMaSP.getText();
            String ten = txtTenSP.getText();
            int soLuong = Integer.parseInt(txtSoLuong.getText());
            double donGia = Double.parseDouble(txtDonGia.getText());

            Sach sachSua = new Sach(ma, ten, soLuong, donGia, "", 0);
            quanLyKhoService.suaSach(sachSua);
            
            JOptionPane.showMessageDialog(this, "Cập nhật thành công!");
            loadDataToTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi nhập liệu!");
        }
    }//GEN-LAST:event_btCapNhatActionPerformed

    //nút xoá
    private void btXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaActionPerformed
        // TODO add your handling code here:
        int row = tblKhoHang.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn 1 dòng trên bảng để xóa!");
            return;
        }
        String maSP = tblKhoHang.getValueAt(row, 0).toString();
        int xacNhan = JOptionPane.showConfirmDialog(this, "Xóa sách mã " + maSP + "?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        
        if (xacNhan == JOptionPane.YES_OPTION) {
            Sach sachXoa = new Sach(maSP, "", 0, 0.0, "", 0);
            quanLyKhoService.xoaSach(sachXoa);
            JOptionPane.showMessageDialog(this, "Xóa thành công!");
            loadDataToTable();
            // Xóa trắng ô nhập liệu sau khi xóa
            txtMaSP.setText(""); txtTenSP.setText(""); txtSoLuong.setText(""); txtDonGia.setText("");
        }
    }//GEN-LAST:event_btXoaActionPerformed

    private void btNhapHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNhapHangActionPerformed
        // TODO add your handling code here:
        try {
            String ma = txtMaSP.getText();
            String ten = txtTenSP.getText();
            int soLuong = Integer.parseInt(txtSoLuong.getText());
            double donGia = Double.parseDouble(txtDonGia.getText());

            Sach sachNhap = new Sach(ma, ten, soLuong, donGia, "", 0);
            quanLyKhoService.nhapHang(sachNhap);
            
            JOptionPane.showMessageDialog(this, "Nhập hàng thành công!");
            loadDataToTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi nhập liệu!");
        }
    }//GEN-LAST:event_btNhapHangActionPerformed

    private void btTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTimKiemActionPerformed
        // TODO add your handling code here:
        // Lấy mã sản phẩm người dùng gõ vào ô nhập liệu
        String maCanTim = txtMaSP.getText().trim();
        
        // Nếu người dùng không nhập gì mà bấm Tìm -> Tải lại toàn bộ bảng
        if (maCanTim.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng nhập Mã Sản Phẩm cần tìm vào ô Mã SP!");
            loadDataToTable(); 
            return;
        }
        
        // Lấy danh sách từ DAO để lọc
        java.util.ArrayList<model.Sach> danhSach = sachDAO.selectAll();
        boolean daThay = false;
        
        if (danhSach != null) {
            tableModel.setRowCount(0); // Xóa trắng bảng để chỉ hiện kết quả tìm kiếm
            
            for (model.Sach s : danhSach) {
                // So sánh mã tìm kiếm (không phân biệt chữ hoa/thường)
                if (s.getMasp().equalsIgnoreCase(maCanTim)) { 
                    
                    // 1. Nạp duy nhất cuốn sách tìm được lên bảng
                    tableModel.addRow(new Object[]{
                        s.getMasp(), 
                        s.getTensp(), 
                        s.getSoluong(), 
                        s.getDongia()
                    });
                    
                    // 2. Điền luôn thông tin lên các ô Text cho tiện thao tác (Sửa/Xóa)
                    txtTenSP.setText(s.getTensp());
                    txtSoLuong.setText(String.valueOf(s.getSoluong()));
                    txtDonGia.setText(String.valueOf(s.getDongia()));
                    
                    daThay = true;
                    break; // Tìm thấy rồi thì dừng vòng lặp luôn
                }
            }
        }
        
        // Nếu vòng lặp chạy xong mà không tìm thấy
        if (!daThay) {
            javax.swing.JOptionPane.showMessageDialog(this, "Không tìm thấy sản phẩm có mã: " + maCanTim);
            loadDataToTable(); // Hiển thị lại toàn bộ danh sách cũ
        }
    }//GEN-LAST:event_btTimKiemActionPerformed

    private void txtDonGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDonGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDonGiaActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCapNhat;
    private javax.swing.JButton btNhapHang;
    private javax.swing.JButton btThem;
    private javax.swing.JButton btThoat;
    private javax.swing.JButton btTimKiem;
    private javax.swing.JButton btXoa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbDonGia;
    private javax.swing.JLabel lbMaSP;
    private javax.swing.JLabel lbSoLuong;
    private javax.swing.JLabel lbTenSP;
    private javax.swing.JTable tblKhoHang;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtMaSP;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTenSP;
    // End of variables declaration//GEN-END:variables
}
